[package]
name = "crate_name"
version = "0.1.0"
authors = ["my nama jeff <email@email.com>"]

# the profile used for 'cargo build'
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# profile used for 'caargo build --release'
[profile.release]
panic = "abort" # disables stack unwinding on panic
